# Generated by Django 3.0.4 on 2020-03-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_auto_20200307_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='description',
        ),
    ]
